
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org:
      hibernate:
        resource:
          transaction: DEBUG
        type:
          descriptor:
            sql: trace
      springframework:
#        web: debug
#        transaction:
#          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
#      com.zaxxer.hikari: TRACE
#      com.zaxxer.hikari.HikariConfig: DEBUG